In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [20]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [21]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df['price'])

LinearRegression()

In [22]:
model.predict([[5000]])

array([859554.79452055])

## Using Pickle

In [23]:
import pickle

In [24]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [25]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [26]:
mp.predict([[5000]])

array([859554.79452055])

## Using Joblib

In [27]:
import joblib

In [28]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [29]:
mj = joblib.load('model_joblib')

In [30]:
mj.predict([[5000]])

array([859554.79452055])

In [31]:
mj.coef_

array([135.78767123])

In [32]:
mj.intercept_

180616.43835616432